create table if not exists public.turns (
  id bigint generated by default as identity primary key,
  session_id text not null,
  turn_number integer not null,
  "timestamp" timestamptz,
  player_decision jsonb not null,
  redcell_response jsonb not null,
  adjudicator_score jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.turns
  add column if not exists session_id text,
  add column if not exists turn_number integer,
  add column if not exists "timestamp" timestamptz,
  add column if not exists player_decision jsonb,
  add column if not exists redcell_response jsonb,
  add column if not exists adjudicator_score jsonb,
  add column if not exists created_at timestamptz default now();

create unique index if not exists idx_turns_session_turn_unique
  on public.turns (session_id, turn_number);

create index if not exists idx_turns_session_id
  on public.turns (session_id);

create index if not exists idx_turns_timestamp
  on public.turns ("timestamp");

alter table public.turns enable row level security;

drop policy if exists "allow read turns" on public.turns;
create policy "allow read turns"
  on public.turns
  for select
  to anon, authenticated
  using (true);

drop policy if exists "allow insert turns" on public.turns;
create policy "allow insert turns"
  on public.turns
  for insert
  to anon, authenticated
  with check (true);
